baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Liam's Portfolio"
theme = 'my-lightbi-hugo-copy'

# (Comment to note important files: themes\my-lightbi-hugo-copy\layouts\partials\homeLayout\profile.html | themes\my-lightbi-hugo-copy\layouts\partials\post_preview_bottom_card.html)

[[menu.main]]
    name = "About"
    url = "/About/"
    weight = 1
    
[[menu.main]]
    name = "Projects"
    url = "/Project List/"
    weight = 2
    
[[menu.main]]
    name = "Resume"
    url = "/Resume/"
    weight = 3

[Params]
    homepageLayout = "profile"
    profileShortbio = "Hello! Thank you for taking the time to check out my website."
    profilePhoto = "img/my-portrait.jpg"
    hideAuthor = false
    comments = false

[module]
  [[module.mounts]]
    disableWatch = false
    source = 'content'
    target = 'content'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'data'
    target = 'data'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'layouts'
    target = 'layouts'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'i18n'
    target = 'i18n'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'archetypes'
    target = 'archetypes'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'assets'
    target = 'assets'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'static'
    target = 'static'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    source = "assets/library/img"
    target = "static/**library**/img"

[caches]
  [caches.images]
    dir = ':cacheDir/images' theme = 'my-lightbi-hugo-copy'
